/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'
import { Route as AdminTatRouteImport } from './routes/admin.tat'
import { Route as AdminPeopleRouteImport } from './routes/admin.people'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiPublicHooksSyncExpertsRouteImport } from './routes/api/public/hooks/sync-experts'
import { Route as ApiPublicHooksBootstrapCredentialsRouteImport } from './routes/api/public/hooks/bootstrap-credentials'

const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTatRoute = AdminTatRouteImport.update({
  id: '/tat',
  path: '/tat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeopleRoute = AdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncExpertsRoute =
  ApiPublicHooksSyncExpertsRouteImport.update({
    id: '/api/public/hooks/sync-experts',
    path: '/api/public/hooks/sync-experts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBootstrapCredentialsRoute =
  ApiPublicHooksBootstrapCredentialsRouteImport.update({
    id: '/api/public/hooks/bootstrap-credentials',
    path: '/api/public/hooks/bootstrap-credentials',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/sync': typeof SyncRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/tat': typeof AdminTatRoute
  '/leads/$id': typeof LeadsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/public/hooks/bootstrap-credentials': typeof ApiPublicHooksBootstrapCredentialsRoute
  '/api/public/hooks/sync-experts': typeof ApiPublicHooksSyncExpertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sync': typeof SyncRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/tat': typeof AdminTatRoute
  '/leads/$id': typeof LeadsIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/public/hooks/bootstrap-credentials': typeof ApiPublicHooksBootstrapCredentialsRoute
  '/api/public/hooks/sync-experts': typeof ApiPublicHooksSyncExpertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/sync': typeof SyncRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/tat': typeof AdminTatRoute
  '/leads/$id': typeof LeadsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/public/hooks/bootstrap-credentials': typeof ApiPublicHooksBootstrapCredentialsRoute
  '/api/public/hooks/sync-experts': typeof ApiPublicHooksSyncExpertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/sync'
    | '/admin/leads'
    | '/admin/people'
    | '/admin/tat'
    | '/leads/$id'
    | '/admin/'
    | '/api/auth/login'
    | '/api/public/hooks/bootstrap-credentials'
    | '/api/public/hooks/sync-experts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sync'
    | '/admin/leads'
    | '/admin/people'
    | '/admin/tat'
    | '/leads/$id'
    | '/admin'
    | '/api/auth/login'
    | '/api/public/hooks/bootstrap-credentials'
    | '/api/public/hooks/sync-experts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/sync'
    | '/admin/leads'
    | '/admin/people'
    | '/admin/tat'
    | '/leads/$id'
    | '/admin/'
    | '/api/auth/login'
    | '/api/public/hooks/bootstrap-credentials'
    | '/api/public/hooks/sync-experts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SyncRoute: typeof SyncRoute
  LeadsIdRoute: typeof LeadsIdRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiPublicHooksBootstrapCredentialsRoute: typeof ApiPublicHooksBootstrapCredentialsRoute
  ApiPublicHooksSyncExpertsRoute: typeof ApiPublicHooksSyncExpertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tat': {
      id: '/admin/tat'
      path: '/tat'
      fullPath: '/admin/tat'
      preLoaderRoute: typeof AdminTatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/people': {
      id: '/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminPeopleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-experts': {
      id: '/api/public/hooks/sync-experts'
      path: '/api/public/hooks/sync-experts'
      fullPath: '/api/public/hooks/sync-experts'
      preLoaderRoute: typeof ApiPublicHooksSyncExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/bootstrap-credentials': {
      id: '/api/public/hooks/bootstrap-credentials'
      path: '/api/public/hooks/bootstrap-credentials'
      fullPath: '/api/public/hooks/bootstrap-credentials'
      preLoaderRoute: typeof ApiPublicHooksBootstrapCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminPeopleRoute: typeof AdminPeopleRoute
  AdminTatRoute: typeof AdminTatRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLeadsRoute: AdminLeadsRoute,
  AdminPeopleRoute: AdminPeopleRoute,
  AdminTatRoute: AdminTatRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SyncRoute: SyncRoute,
  LeadsIdRoute: LeadsIdRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiPublicHooksBootstrapCredentialsRoute:
    ApiPublicHooksBootstrapCredentialsRoute,
  ApiPublicHooksSyncExpertsRoute: ApiPublicHooksSyncExpertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
