/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiPublicHooksSyncExpertsRouteImport } from './routes/api/public/hooks/sync-experts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncExpertsRoute =
  ApiPublicHooksSyncExpertsRouteImport.update({
    id: '/api/public/hooks/sync-experts',
    path: '/api/public/hooks/sync-experts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/public/hooks/sync-experts': typeof ApiPublicHooksSyncExpertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/public/hooks/sync-experts': typeof ApiPublicHooksSyncExpertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/public/hooks/sync-experts': typeof ApiPublicHooksSyncExpertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/auth/login' | '/api/public/hooks/sync-experts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/auth/login' | '/api/public/hooks/sync-experts'
  id: '__root__' | '/' | '/api/auth/login' | '/api/public/hooks/sync-experts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiPublicHooksSyncExpertsRoute: typeof ApiPublicHooksSyncExpertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-experts': {
      id: '/api/public/hooks/sync-experts'
      path: '/api/public/hooks/sync-experts'
      fullPath: '/api/public/hooks/sync-experts'
      preLoaderRoute: typeof ApiPublicHooksSyncExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiPublicHooksSyncExpertsRoute: ApiPublicHooksSyncExpertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
